= Pivotal Cloud Foundry 101 Workshop - ESI

== Schedule

This one day hands-on classroom style session will provide developers with hands on experience with Pivotal Cloud Foundry concepts, architecture and fundamentals of pushing code and building applications. The session includes presentations, demos and hands on labs

8:00 AM - 8:30 AM	Breakfast and Registration

				Enjoy breakfast with the team
8:30 AM - 9:00 AM	Kickoff
				Where we are and where we are going
9:00 AM - 10:00 AM	Cloud Native Introduction
				Industry Trends and Overview including: 12 Factor Apps, Microservices and Cloud Platforms
10:00 AM - 10:15 AM	Break
10:15 AM - 11:15 AM	Pivotal Cloud Foundry
			An overview of PCF and its Architecture
11:15 AM - 12:00 PM	Services Made Easy
				PCF Services (Database, Messaging, etc.) and the Marketplace
12:00 PM - 12:30 PM	Lunch
				Lunch will be provided
12:30 PM - 2:00 PM	Spring Boot Primer
				Getting started with Spring Boot.  Let’s make an app!
2:00 PM - 3:00 PM		The Cloud Native Enterprise
					Devops, Continuous Delivery, Microservices, what’s new, what isn’t, what matters 
3:00 PM - 3:15 PM		Break
3:15 PM - 4:30 PM		Developer Workshop
Hands-on pushing code with PCF
4:30 PM - 5:00 PM		Wrap Up, Q&A, Feedback

== Course Materials

* Session 1: link:presentations/Session_1_Introduction.pptx[Introduction]
* Session 2: link:presentations/Session_2_Architecture_And_Operations.pptx[Pivotal Cloud Foundry Architecture and Operations]
* Session 3: link:presentations/Session_3_Cloud_Native_Enterprise.pptx[The Cloud Native Enterprise]
* Session 4: link:presentations/Session_4_Services_Overview.pptx[Pivotal Cloud Foundry Services]

* Developer Workshop
** Pre-work
*** link:labs/labaccess.adoc[Get Environment Access]
** Lab 1 - From Zero to Pushing Your First Application
*** link:labs/lab1/lab.adoc[**Java** Application]
*** link:labs/lab1/lab-ruby.adoc[**Ruby** Application]
** link:labs/lab2/lab.adoc[Lab 2 - Binding to Cloud Foundry Services]
** link:labs/lab3/lab.adoc[Lab 3 - Operating Your Application]
** link:labs/lab4/lab.adoc[Lab 4 - Monitoring Your Application]
** link:labs/lab5/continuous-delivery-lab.adoc[Advanced Lab - Jenkins Integration]
