---
resources:
- name: cf-workshop-demo
  type: git
  source:
    uri: https://github.com/bjimerson-pivotal/cf-workshop-demo
    branch: master
- name: cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: deploy-app
  plan:
  - get: cf-workshop-demo
  - task: package
    file: cf-workshop-demo/ci/tasks/package.yml
  - put: cf
    params:
      manifest: cf-workshop-demo/manifest.yml
